language: ruby

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.1

gemfile:
  - Gemfile.3.2.mysql2
  - Gemfile.4.2.mysql2
  - Gemfile.4.2.pg
  - Gemfile.5.0.mysql2
  - Gemfile.5.0.pg

dist: trusty

matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: Gemfile.5.0.mysql2
    - rvm: 2.1.8
      gemfile: Gemfile.5.0.pg

install:
  # This is the default Travis CI install step
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - psql -c 'create database has_defaults_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS has_defaults_test;'

script: bundle exec rake current_rspec

sudo: false

cache: bundler

notifications:
  email:
    - fail@makandra.de
